pybullet:
  simulation:
    gravity: [0, 0, -9.81]
    time_step: 0.016666666666666666
    num_solver_iterations: 5
    num_substeps: 1
  robot:
    urdf_path: "/urdf/tt.urdf"
    start_position: [0, 0, 0.175]
    start_orientation: [1.5707963267948966, 0, -3.1415926535897932]
    power: 16 #Watt 
    max_robot_angular_velocity: 1 #rad/s
task:
  goal_radius: 5
  goal_angle_bounds: [-45, 45]
  smoothing_factor: 0.9
  distance_threshold: 0.05
  fall_threshold: 0.13
  fall_reward: -25.0
  forward_velocity_bias: 0.8
  pitch_bias: 20
  max_angle_dip: 0.785398 # RADIANS!
standing_task:
  angle_dip_bias: .5
  smoothing_factor: .40
  action_smoothing_factor: 10
  jump_penalty: 0.75
  up_threshold: 0.4
  time_emphasis: 0.2
  time_threshold: 2000.0
  plane_angle_bounds: 15 # +/- 5 degrees
  max_angle_dip: 0.523599 # RADIANS!
  max_angle_dev: 5
  desired_position: [0, 0, 0.28]
  good_position_reward: 5.0
  bad_position_penalty: .8
  distance_threshold: 0.05
  initial_angles: [-0.0, 1.5707963267948963, -3.141592653589793]
rmps:
  force_vector_empahsis: [0.75, 1.5, 0.75]
  alpha: 1.0
  beta: 4.5
stability_policy:
  Kp: 1.0
  Kd: 0.01
stability_metric:
  z_position_emphasis: 10.0
  pitch_emphasis: 10.0
target_policy:
  Kp: 1.0
  Kd: 0.01
target_metric:
  force_x_emphasis: 10.0  
  force_y_emphasis: 10.0